background {
    path = screenshot 

    blur_passes = 3
}

# --- TIME ---
label {
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba(255, 255, 255, 1.0)
    font_size = 200
    font_family = Noto Sans Mono

    position = 0, 200
}

# --- DATE ---
label {
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.7)
    font_size = 50
    font_family = Noto Sans Mono

    position = 0, 0
}

input-field {
    dots_size = 0.5
    dots_spacing = 0.5

    font_color = rgba(255, 255, 255, 0.7)
    outer_color = rgba(0, 0, 0, 0.0)
    inner_color = rgba(0, 0, 0, 0.0)
    check_color = rgba(0, 0, 0, 0.0)
    fail_color = rgba(0, 0, 0, 0.0)

    placeholder_text = 

    position = 0, -150
}
